#!/bin/bash

COMPOSE_ROOT=/boot/config/plugins/compose.manager/projects
COMPOSE_WRAPPER=/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh

while read dir; do
   if [ "true" != "$(cat ${dir}/autostart)" ]; then
       continue
   fi
   if [ ! -f "${dir}/compose.yml" ]; then
       continue
   fi
   logger "Starting compose stack: $(cat ${dir}/name)"
   $COMPOSE_WRAPPER up "${dir}/compose.yml" "$(cat ${dir}/name)" > /dev/null &
done <<< $(find $COMPOSE_ROOT -type f -name autostart -exec dirname {} \;)

wait
