#!/bin/bash

COMPOSE_ROOT=/boot/config/plugins/compose.manager/projects
COMPOSE_WRAPPER=/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh

while read dir; do
    # echo "${dir}/compose"
    logger "Stopping compose stack: $(cat ${dir}/name)"
    $COMPOSE_WRAPPER stop "${dir}/compose" "$(cat ${dir}/name)" > /dev/null&
done <<< $(find $COMPOSE_ROOT -type f -name compose.yml -exec dirname {} \;)

wait
